### ISSUE TITLE
404 after build 

### ISSUE THREAD

**Issue by Fanom2813** [iuroc/vanjs-router#2]
Hi , I am new to vanjs , i run vanjs with vite and. vanjs-routing, after building to production when i access routes it returns 404, how can i fix ? thanks here is my code 

```
import van from "vanjs-core";
import { Router} from "vanjs-routing";

import HomePage from "./pages/home";
import AboutPage from "./pages/about";
import PrivacyPolicyPage from "./pages/privacy";
import TermsPage from "./pages/terms";
import RefundPolicy from "./pages/refund-policy";

function App() {
  return Router({
    routes: [
      { path: "/", component: HomePage },
      { path: "/about", component: AboutPage },
      { path: "/privacy-policy", component: PrivacyPolicyPage },
      { path: "/terms-and-conditions", component: TermsPage },
      { path: "/refund-policy", component: RefundPolicy }
    ]
  });
}

van.add(document.body, App());
```

**Comment by groovenectar** [comment]
Is Vite necessary? With VanJS you don't need to use a build step if you're not using Typescript...

Just add this to an HTML file:

```
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/vanjs-org/van/public/van-1.2.7.nomodule.min.js"></script>
```

**Comment by iuroc** [comment]
> Is Vite necessary? With VanJS you don't need to use a build step if you're not using Typescript...
> 
> Just add this to an HTML file:
> 
> ```
> <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/vanjs-org/van/public/van-1.2.7.nomodule.min.js"></script>
> ```

The Van framework facilitates the direct construction of native DOM, allowing for easy application in web development without the need for cumbersome configurations. However, for those seeking an even more refined modular development experience, considering the npm approach is advisable. Not only does the Van framework assist in the straightforward construction of native DOM for seamless web application development, but it also offers a highly convenient option through direct CDN imports, providing developers with greater flexibility in their choices.

**Comment by iuroc** [comment]
> Hi , I am new to vanjs , i run vanjs with vite and. vanjs-routing, after building to production when i access routes it returns 404, how can i fix ? thanks here is my code
> 
> ```
> import van from "vanjs-core";
> import { Router} from "vanjs-routing";
> 
> import HomePage from "./pages/home";
> import AboutPage from "./pages/about";
> import PrivacyPolicyPage from "./pages/privacy";
> import TermsPage from "./pages/terms";
> import RefundPolicy from "./pages/refund-policy";
> 
> function App() {
>   return Router({
>     routes: [
>       { path: "/", component: HomePage },
>       { path: "/about", component: AboutPage },
>       { path: "/privacy-policy", component: PrivacyPolicyPage },
>       { path: "/terms-and-conditions", component: TermsPage },
>       { path: "/refund-policy", component: RefundPolicy }
>     ]
>   });
> }
> 
> van.add(document.body, App());
> ```

Please check if there are any errors in the route paths and ensure that the DOM components are returned correctly. Additionally, you might want to consider using the [VanJS Router](https://github.com/iuroc/vanjs-router) that I've developed, as it could be simpler and more efficient.
